apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-assignment
  template:
    metadata:
      labels:
        app: mlops-assignment
    spec:
      containers:
        - name: mlops-assignment
          image: <DOCKERHUB_USERNAME>/mlops_assignment:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
